INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Conjunto Roupa Junina P/m', 89.9, 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.elo7.com.br%2Fconjunto-roupa-junina-p-m%2Fdp%2F16D0018&psig=AOvVaw2mc0QL04JKSYC0k3D0ZJrc&ust=1678120141941000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCODAyeiaxf0CFQAAAAAdAAAAABAE', 'Conjunto CROPPED + SAIA serve tamanho adulto P e M.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Conjunto Feminino', 59.9, 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.bellucymodas.com.br%2Fprodutos%2Fconjunto-feminino-detalhes-em-botao-roupas-feminanas-moda1%2F&psig=AOvVaw2mc0QL04JKSYC0k3D0ZJrc&ust=1678120141941000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCODAyeiaxf0CFQAAAAAdAAAAABAI', 'Conjunto Feminino Detalhes Em Botão Roupas Feminanas Moda.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Conjunto Feminino Blusa Short Roupas Femininas', 68.0, 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.magazineluiza.com.br%2Fconjunto-feminino-blusa-short-roupas-femininas-bellucy-modas%2Fp%2Fhebgb6d916%2Fmd%2Fcrfe%2F&psig=AOvVaw2mc0QL04JKSYC0k3D0ZJrc&ust=1678120141941000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCODAyeiaxf0CFQAAAAAdAAAAABAS', 'Conjunto Feminino Blusa Short Roupas Femininas - Bellucy Modas.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Conjunto Feminino Cropped Short Estampado Roupa Feminina', 52.0, 'https://www.google.com/url?sa=i&url=https%3A%2F%2Fwww.shoptime.com.br%2Fbusca%2Fconjunto-de-roupa-feminino&psig=AOvVaw2mc0QL04JKSYC0k3D0ZJrc&ust=1678120141941000&source=images&cd=vfe&ved=0CBAQjRxqFwoTCODAyeiaxf0CFQAAAAAdAAAAABAc', 'Conjunto Feminino Cropped Short Estampado Roupa Feminina.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Risoto Funghi', 59.95, 'https://raw.githubusercontent.com/devsuperior/sds2/master/assets/risoto_funghi.jpg', 'Risoto Funghi feito com ingredientes finos e o toque especial do chef.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Macarrão Espaguete', 35.9, 'https://raw.githubusercontent.com/devsuperior/sds2/master/assets/macarrao_espaguete.jpg', 'Macarrão fresco espaguete com molho especial e tempero da casa.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Macarrão Fusili', 38.0, 'https://raw.githubusercontent.com/devsuperior/sds2/master/assets/macarrao_fusili.jpg', 'Macarrão fusili com toque do chef e especiarias.');
INSERT INTO tb_product (name, price, image_Uri, description) VALUES ('Macarrão Penne', 37.9, 'https://raw.githubusercontent.com/devsuperior/sds2/master/assets/macarrao_penne.jpg', 'Macarrão penne fresco ao dente com tempero especial.');

INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T10:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -22.946779, -43.217753, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T15:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -25.439787, -49.237759, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T16:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T12:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (1, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T08:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T14:00:00Z');
INSERT INTO tb_order (status, latitude, longitude, address, moment) VALUES (0, -23.561680, -46.656139, 'Avenida Paulista, 1500', TIMESTAMP WITH TIME ZONE '2021-01-01T09:00:00Z');

INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (1 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (2 , 8);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 3);
INSERT INTO tb_order_product (order_id, product_id) VALUES (3 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 2);
INSERT INTO tb_order_product (order_id, product_id) VALUES (4 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 4);
INSERT INTO tb_order_product (order_id, product_id) VALUES (5 , 6);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 5);
INSERT INTO tb_order_product (order_id, product_id) VALUES (6 , 1);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 7);
INSERT INTO tb_order_product (order_id, product_id) VALUES (7 , 5);